#!/usr/bin/env python3
"""
AART brake-module table generator.

Builds the paired brake / anti-brake lookup tables used in Mode B and the
soft endpoints used by the linear maps in Modes A and C. Emits C source
ready to paste into brake_module.c.

CONCEPT
-------
One pot position (index 0..255) drives TWO outputs at once:

  brake_dac[idx]  -> Q2 gate (more braking as idx rises, CCW->CW)
  ka_dac[idx]     -> Q1 gate (LESS anti-brake as idx rises)

Both are 12-bit DAC codes (0..4095), i.e. gate-drive levels, NOT ohms or
volts. They become gate voltages through the op-amp buffers. The mapping
from a DAC code to an actual resistance / injection voltage is FET-,
temperature- and current-dependent and must be calibrated on the bench;
the numbers here are starting estimates.

Brake codes:  higher code = higher Q2 gate = lower Rds = MORE braking.
Anti-brake:   lower  code = MORE Q1 conduction = MORE injection.
              DAC_KA_OFF (4095) = Q1 fully off = no anti-brake.

PROFILES
--------
Each profile is one selectable "minimum brake resistance" setting. A profile
specifies:
  - label_ohms : nominal full-scale (CCW / softest) resistance, for the UI
  - brake_soft : DAC at idx 0   (CCW, gentlest brake)
  - brake_hard : DAC at idx 255 (CW, dead short) - normally DAC_BRAKE_HARD
  - brake_gamma: curve shape for the brake sweep (1.0 = linear,
                 >1 = fine control at the soft end)
  - ka_max     : DAC at idx 0   (CCW, maximum anti-brake injection)
  - ka_off     : DAC at idx where anti-brake reaches zero (Q1 off)
  - ka_gamma   : curve shape for the anti-brake sweep
  - ka_zero_at : pot index fraction (0..1) at which anti-brake hits zero,
                 so anti-brake can fade out before full CW if you want.

You can give every profile the same shape (pure endpoint scaling) or hand
-tune each curve independently - this is exactly the flexibility that makes
storing five full tables worthwhile.
"""

from dataclasses import dataclass, field

# ---- Fixed hardware/firmware constants (match brake_module.h) -------------
DAC_MAX        = 4095
DAC_BRAKE_HARD = 3095   # pot CW dead short
DAC_KA_OFF     = 4095   # Q1 off, no anti-brake
TABLE_LEN      = 256


@dataclass
class Profile:
    label_ohms: int
    brake_soft: int
    brake_hard: int = DAC_BRAKE_HARD
    brake_gamma: float = 1.8
    ka_max: int = 2480          # ~2V max injection
    ka_off: int = DAC_KA_OFF
    ka_gamma: float = 1.8
    ka_zero_at: float = 0.65    # anti-brake reaches zero at 65% of travel


def _curve(i, n, lo, hi, gamma):
    """Map index i in [0, n-1] to a value in [lo, hi] with gamma shaping.
    gamma = 1.0 is linear; gamma > 1.0 puts fine resolution near lo."""
    if n <= 1:
        return lo
    frac = (i / (n - 1)) ** gamma
    return round(lo + (hi - lo) * frac)


def make_brake_table(p: Profile):
    """Brake DAC sweep: soft (CCW) -> hard (CW). Monotonic up."""
    return [max(p.brake_soft, min(p.brake_hard,
            _curve(i, TABLE_LEN, p.brake_soft, p.brake_hard, p.brake_gamma)))
            for i in range(TABLE_LEN)]


def make_ka_table(p: Profile):
    """Anti-brake DAC sweep: ka_max (CCW, most injection) -> ka_off (none).

    Reaches ka_off at index = ka_zero_at * 255, then stays off to CW.
    Note: because lower DAC = more injection, this sweep moves UP from
    ka_max toward ka_off as the pot turns CW (anti-brake fades out)."""
    zero_idx = max(1, int(round(p.ka_zero_at * (TABLE_LEN - 1))))
    out = []
    for i in range(TABLE_LEN):
        if i >= zero_idx:
            out.append(p.ka_off)
        else:
            # sweep ka_max -> ka_off over [0, zero_idx]
            v = _curve(i, zero_idx + 1, p.ka_max, p.ka_off, p.ka_gamma)
            out.append(max(min(p.ka_max, p.ka_off), min(max(p.ka_max, p.ka_off), v)))
    return out


# ---- Default profile set: non-linear 2/3/4/6/8 ohm ------------------------
# Same gamma shape across all five (pure endpoint scaling). Edit freely:
# give the low-ohm brushless profiles a different brake_gamma or ka curve
# if you want a distinct feel per motor type.
DEFAULT_PROFILES = [
    Profile(label_ohms=2, brake_soft=2300, brake_gamma=1.8, ka_max=2480, ka_zero_at=0.65),
    Profile(label_ohms=3, brake_soft=2200, brake_gamma=1.8, ka_max=2480, ka_zero_at=0.65),
    Profile(label_ohms=4, brake_soft=2100, brake_gamma=1.8, ka_max=2480, ka_zero_at=0.65),
    Profile(label_ohms=6, brake_soft=1950, brake_gamma=1.8, ka_max=2480, ka_zero_at=0.65),
    Profile(label_ohms=8, brake_soft=1860, brake_gamma=1.8, ka_max=2480, ka_zero_at=0.65),
]


def emit_c(profiles, single_ka=True):
    """Emit C source for brake_module.c.

    single_ka=True emits ONE shared ka_dac_table (anti-brake identical across
    profiles - the common case). Set False to emit a per-profile ka table."""
    n = len(profiles)
    lines = []
    lines.append(f"/* Auto-generated by gen_brake_tables.py. Do not hand-edit. */")
    lines.append(f"/* {n} profiles, labels: " +
                 ", ".join(f"{p.label_ohms}\u03a9" for p in profiles) + " */\n")

    # ohm labels
    lines.append(f"static const uint16_t brake_ohms_label[BRAKE_OHMS_COUNT] = {{")
    lines.append("    " + ", ".join(str(p.label_ohms) for p in profiles) + ",")
    lines.append("};\n")

    # soft endpoints (used by Mode A/C linear maps)
    lines.append(f"static const uint16_t brake_soft_dac_by_ohm[BRAKE_OHMS_COUNT] = {{")
    lines.append("    " + ", ".join(str(p.brake_soft) for p in profiles) + ",")
    lines.append("};\n")

    # brake tables
    lines.append(f"static const uint16_t brake_tables[BRAKE_OHMS_COUNT][256] = {{")
    for k, p in enumerate(profiles):
        t = make_brake_table(p)
        lines.append(f"  /* index {k}: ~{p.label_ohms} ohm "
                     f"(soft={p.brake_soft}, gamma={p.brake_gamma}) */")
        lines.append("  {")
        for r in range(0, TABLE_LEN, 16):
            lines.append("    " + ", ".join(f"{v:4d}" for v in t[r:r+16]) + ",")
        lines.append("  },")
    lines.append("};\n")

    # anti-brake table(s)
    if single_ka:
        t = make_ka_table(profiles[0])
        lines.append(f"/* Shared anti-brake table (Mode B). Same for all profiles. */")
        lines.append(f"static const uint16_t ka_dac_table[256] = {{")
        for r in range(0, TABLE_LEN, 16):
            lines.append("    " + ", ".join(f"{v:4d}" for v in t[r:r+16]) + ",")
        lines.append("};")
    else:
        lines.append(f"static const uint16_t ka_tables[BRAKE_OHMS_COUNT][256] = {{")
        for k, p in enumerate(profiles):
            t = make_ka_table(p)
            lines.append(f"  /* index {k}: ~{p.label_ohms} ohm anti-brake */")
            lines.append("  {")
            for r in range(0, TABLE_LEN, 16):
                lines.append("    " + ", ".join(f"{v:4d}" for v in t[r:r+16]) + ",")
            lines.append("  },")
        lines.append("};")

    # flash cost note
    brake_bytes = n * TABLE_LEN * 2
    ka_bytes = TABLE_LEN * 2 if single_ka else n * TABLE_LEN * 2
    total = brake_bytes + ka_bytes + n * 2 + n * 2
    lines.append("")
    lines.append(f"/* Flash cost: brake {brake_bytes} B + ka {ka_bytes} B "
                 f"+ labels/endpoints {n*4} B = {total} B total. */")
    return "\n".join(lines)


if __name__ == "__main__":
    import sys
    single = "--per-profile-ka" not in sys.argv
    print(emit_c(DEFAULT_PROFILES, single_ka=single))
